### ISSUE TITLE
ValueError: Missing staticfiles manifest entry for 'plugins/css/bootstrap.min.css'

### ISSUE THREAD

**Issue by the-black-knight-01** [Yawan-1/StackOverFlow--Clone#2]
![image](https://user-images.githubusercontent.com/39003714/149315678-d52aaaec-f782-47b3-ac54-0e9660f4c30c.png)
uring handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/Users/admin/anaconda3/lib/python3.6/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 133, in __call__
    response = self.get_response(request)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 130, in get_response
    response = self._middleware_chain(request)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 49, in inner
    response = response_for_exception(request, exc)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 114, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/Users/admin/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 153, in handle_uncaught_exception
    return callback(request)
  File "/Users/admin/StackOverFlow--Clone/qa/views.py", line 64, in handler500
    return render(request, 'home/500.html')
  File "/Users/admin/.local/lib/python3.6/site-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/templatetags/static.py", line 106, in render
    url = self.url(context)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/templatetags/static.py", line 103, in url
    return self.handle_simple(path)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/templatetags/static.py", line 118, in handle_simple
    return staticfiles_storage.url(path)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 147, in url
    return self._url(self.stored_name, name, force)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 126, in _url
    hashed_name = hashed_name_func(*args)
  File "/Users/admin/.local/lib/python3.6/site-packages/django/contrib/staticfiles/storage.py", line 417, in stored_name
    raise ValueError("Missing staticfiles manifest entry for '%s'" % clean_name)
ValueError: Missing staticfiles manifest entry for 'plugins/css/bootstrap.min.css'
[13/Jan/2022 15:59:35] "GET /favicon.ico HTTP/1.1" 500 59
```

**Comment by Yawan-1** [comment]
Try, running run server with **Debug = True**

**Comment by saugatrajbhandari** [comment]
@Yawan-1 it works on **DEBUG=True**
